manifest:
  remotes:
    - name: waffle87
      url-base: https://github.com/waffle87
  projects:
    - name: revxlp
      remote: waffle87
      revision: main
    - name: flake_dongle
      remote: waffle87
      revision: main
    - name: flake
      remote: waffle87
      revision: main
  self:
    path: config
